app/urls.py
from django.urls import path, include, re_path
from . import views
from django.contrib.auth.decorators import login_required
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.conf import settings
from django.views.static import serve

admin.autodiscover()
admin.site.login = login_required(admin.site.login)

app_name = 'app'

urlpatterns = [    
    path('onboard/', views.Onboard.as_view(), name="onboard"),
    path('dashboard/<str:id>/', views.Dashboard.as_view(), name='dashboard'),
    path('dashboard/', views.Dashboard.as_view(), name="dashboard"),    
    path('api/setup_user/', views.Setup_user.as_view(), name="setup_user"),
    path('api/chat/', views.Chat.as_view(), name="chat"),
    path('api/update_db/', views.Update_db.as_view(), name="update_db"),
    path('user_profile/', views.UserProfile.as_view(), name="user_profile"),
    path('update_profile/', views.Update_profile.as_view(), name='update_profile'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('', include('users.urls')),
    path('', include('subscriptions.urls')),
    path('', include('social_django.urls')),
    path('admin/', admin.site.urls),
]

SOCIAL_AUTH_URL_NAMESPACE = 'social'

users/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import (
    login_view,
    logout_view,
    forgot_password_view,
    registeration_view,
    check_otp_view,
    check_reset_otp_view,
    reset_new_password_view,
)

from . import views

app_name = 'users'

urlpatterns = [
    path('', views.Home.as_view(), name="home"),
    path('sign_in/', login_view, name='sign_in'),
    path('logout/', logout_view, name='logout'),
    path('sign_up/', registeration_view, name='sign_up'),
    path('forgot-password/', forgot_password_view, name='forgot_password'),
    path('activate-email/', check_otp_view, name='activate_email'),
    path('reset-code/', check_reset_otp_view, name='reset_code'),
    path('new-password/', reset_new_password_view, name='reset_new_password'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from os import path


def get_profile_picture_filepath(instance, filename):
    filename = filename.split('.')[-1]
    return path.join('profile_images', '{}profile_image.{}'.format(instance.pk, filename))


class CustomUser(AbstractUser):
    profile_picture = models.ImageField(
        _('profile picture'), upload_to=get_profile_picture_filepath, null=True, blank=True)
    bio = models.TextField(_('Bio'), max_length=500, blank=True)
    short_bio = models.TextField(_('Short Bio'), max_length=250, blank=True)
    source = models.CharField(_('source'), max_length=50, blank=True)
    docs_left = models.IntegerField(default=2)
    usage = models.IntegerField(default=0)
    user_plan = models.TextField(default="Free")
    subscription_status = models.CharField(max_length=300,blank=True, null=True)
    first_name = models.TextField(blank=True, null=True)
    last_name = models.TextField(blank= True, null=True)
    token = models.TextField(blank=True, null=True)
    subdomain = models.TextField(blank=True, null=True)
    


class OtpCode(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    code = models.CharField(max_length=20, unique=True)
    email = models.EmailField(blank=True)

    def __str__(self):
        return self.code

users/forms.py
from django.contrib.auth import get_user_model, password_validation
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.forms import widgets
from django.utils.translation import gettext_lazy as _
from django.core.validators import validate_email
from django import forms
from users.models import OtpCode


class CustomLoginForm(forms.Form):
    username_or_email = forms.CharField(
        max_length=256,
        label='Username or Email',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username or Email'}) 
    )
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Password'}))
    

    def clean_username_or_email(self):
        username_or_email = self.cleaned_data['username_or_email']
        if "@" in username_or_email:
            validate_email(username_or_email)
            data = {'email': username_or_email}
        else:
            data = {'username': username_or_email}
        try:
            get_user_model().objects.get(**data)
        except get_user_model().DoesNotExist:
            raise ValidationError(
                _('This {} does not exist'.format(list(data.keys())[0])))
        else:
            return username_or_email


class RegisterForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget = widgets.TextInput(
            attrs={'placeholder': "username", "class": "form-control"})
        self.fields['email'].widget = widgets.EmailInput(
            attrs={'placeholder': "email", "class": "form-control"})
        self.fields['password1'].widget = widgets.PasswordInput(
            attrs={'placeholder': "password", "class": "form-control"})
        self.fields['password2'].widget = widgets.PasswordInput(
            attrs={'placeholder': "repeat password", "class": "form-control"})

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise ValidationError("This email address is already exists.")
        return email

    class Meta:
        model = get_user_model()
        fields = ("username", "email")


class ForgetPasswordEmailCodeForm(forms.Form):
    username_or_email = forms.CharField(max_length=256,
                                        widget=forms.TextInput(
                                            attrs={'class': 'form-control ',
                                                   'placeholder': 'Type your email'}
                                        )
                                        )

    def clean_username_or_email(self):
        username_or_email = self.cleaned_data['username_or_email']
        data = {'username': username_or_email}

        if '@' in username_or_email:
            validate_email(username_or_email)
            data = {'email': username_or_email}
        try:
            get_user_model().objects.get(**data)
        except get_user_model().DoesNotExist:
            raise ValidationError(
                'There is no account with this {}'.format(list(data.keys())[0]))

        if not get_user_model().objects.get(**data).is_active:
            raise ValidationError(_('This account is not active.'))

        return data


class ChangePasswordForm(forms.Form):
    new_password1 = forms.CharField(
        label="New password",
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'New password'
            }
        ),
    )
    new_password2 = forms.CharField(
        label="Confirm password",
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Confirm password',
            }
        ),
    )

    def clean_new_password2(self):
        password1 = self.cleaned_data['new_password1']
        password2 = self.cleaned_data['new_password2']

        if password1 and password2 and password1 != password2:
            raise ValidationError(_('Passwords are not match'))
        password_validation.validate_password(password2)
        return password2


class OtpForm(forms.Form):
    otp = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Enter code',
            }
        )
    )

    def clean_otp(self):
        otp_code = self.cleaned_data['otp']
        try:
            OtpCode.objects.get(code=otp_code)
        except OtpCode.DoesNotExist:
            raise ValidationError(
                _('You have entered incorrect code!')
            )
        else:
            return otp_code

users/views.py
from django.contrib.auth import (
    authenticate,
    get_user_model,
    login,
    logout,
)
from django.contrib.auth.hashers import make_password
from django.utils.translation import gettext_lazy as _
from django.contrib import messages
from django.utils.crypto import get_random_string
from django.shortcuts import (
    redirect,
    render,
)
from django.views import View

from django.contrib.auth.decorators import login_required

from .forms import (
    CustomLoginForm,
    RegisterForm,
    ForgetPasswordEmailCodeForm,
    ChangePasswordForm,
    OtpForm,
)
from .models import OtpCode, CustomUser
from .utils import (
    send_activation_code,
    send_reset_password_code,
)
from .decorators import only_authenticated_user, redirect_authenticated_user

class Home(View):
    template = "home.html"
    def get(self, request, *args, **kwargs):
        context = {}
        print(request.user)
        return render(self.request, self.template, context)

@redirect_authenticated_user
def login_view(request):
    error = None
    if request.method == 'POST':
        form = CustomLoginForm(request.POST)
        if form.is_valid():
            user = authenticate(
                request, username=form.cleaned_data['username_or_email'], password=form.cleaned_data['password'])
            if user:
                if user.is_active:  #                 if not user.is_active:
                    messages.warning(request, _(
                        f"It's look like you haven't still verify your email - {user.email}"))
                    return redirect('users:activate_email')
                else:
                    login(request, user)
                    return redirect('app:dashboard')
            else:
                error = 'Invalid Credentials'
    else:
        form = CustomLoginForm()
    return render(request, 'users/sign_in.html', {'form': form, 'error': error, 'SOCIALS': True})


@only_authenticated_user
@login_required
def logout_view(request):
    logout(request)
    return redirect('users:sign_in')


@redirect_authenticated_user
def registeration_view(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST or None)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.source = 'Register'
            user.save(True)

            # code = get_random_string(20)
            # otp = OtpCode(code=code, user=user)
            # otp.save(True)
            # try:
            #     send_activation_code(user.email, code)
            # except:
            #     otp.delete()
            #     user.delete()
            #     messages.error(request, _('Failed while sending code!'))
            # else:
            #     messages.success(
            #         request, _(f'We have sent a verification code to your email - {user.email}'))

            return redirect('users:sign_in')
                # return redirect('users:activate_email')
    else:
        form = RegisterForm()
    return render(request, 'users/sign_up.html', {'form': form, 'SOCIALS': True})


@redirect_authenticated_user
def forgot_password_view(request):
    if request.method == 'POST':
        form = ForgetPasswordEmailCodeForm(request.POST)
        if form.is_valid():
            username_or_email = form.cleaned_data['username_or_email']
            user = get_user_model().objects.get(**username_or_email)
            code = get_random_string(20)

            otp = OtpCode(code=code, user=user, email=user.email)
            otp.save()

            try:
                send_reset_password_code(user.email, code)
            except:
                otp.delete()
                messages.error(request, _('Failed while sending code!'))
            else:
                messages.success(request, _(
                    f"We've sent a passwrod reset otp to your email - {user.email}"))
                return redirect('users:reset_code')
    else:
        form = ForgetPasswordEmailCodeForm()
    return render(request, 'users/forgot_password.html', context={'form': form})

@redirect_authenticated_user
def check_otp_view(request):
    if request.method == 'POST':
        form = OtpForm(request.POST)
        if form.is_valid():
            otp = OtpCode.objects.get(code=form.cleaned_data['otp'])
            user = otp.user
            otp.delete()
            user.is_active = True
            user.save()
            return redirect('users:sign_in')
    else:
        form = OtpForm()
    return render(request, 'users/user_otp.html', {'form': form})

@redirect_authenticated_user
def check_reset_otp_view(request):
    if request.method == 'POST':
        form = OtpForm(request.POST)
        if form.is_valid():
            otp = OtpCode.objects.get(code=form.cleaned_data['otp'])
            request.session['email'] = otp.user.email
            messages.success(request, _(
                "Please create a new password that you don't use on any other site."))
            return redirect('users:reset_new_password')
    else:
        form = OtpForm()
    return render(request, 'users/user_otp.html', {'form': form})


@redirect_authenticated_user
def reset_new_password_view(request):
    if request.method == 'POST':
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            email = request.session['email']
            del request.session['email']
            user = CustomUser.objects.get(email=email)
            user.password = make_password(form.cleaned_data["new_password2"])
            user.save()
            messages.success(request, _(
                "Your password changed. Now you can login with your new password."))
            return redirect('users:sign_in')
    else:
        form = ChangePasswordForm()
    return render(request, 'users/new_password.html', {'form': form})

users/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>{% block title %} {% endblock %}</title>

      {% load static %}
      <!-- CSS files -->
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:400,700">
      <script src="https://cdn.jsdelivr.net/npm/@tabler/core@1.0.0-beta17/dist/js/tabler.min.js"></script>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/core@1.0.0-beta17/dist/css/tabler.min.css">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/core@1.0.0-beta17/dist/css/tabler-flags.min.css">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/core@1.0.0-beta17/dist/css/tabler-payments.min.css">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/core@1.0.0-beta17/dist/css/tabler-vendors.min.css">
      <link rel="stylesheet" href="{% static 'css/styles.css' %}">
      <style>
         @import url('https://rsms.me/inter/inter.css');
         :root {
            --tblr-font-sans-serif: 'Inter Var', -apple-system, BlinkMacSystemFont, San Francisco, Segoe UI, Roboto, Helvetica Neue, sans-serif;
         }
         body {
            font-feature-settings: "cv03", "cv04", "cv11";
         }
      </style>
   </head>
   <body>

      {% block navbar %}{% endblock navbar %}
      {% block content %}{% endblock %}

   </body>
</html>

users/templates/users/forgot_password.html
{% extends "./base.html" %}
{% load static %}

{%block title%}
Password reset
{%endblock title%}

{% block content %}
{%if error%}
<div class="alert alert-danger" role="alert">
    {{error}}
</div>
{%endif%}

<div class=" d-flex flex-column">
    <script src="./dist/js/demo-theme.min.js?1685976846"></script>
    <div class="page page-center">
      <div class="container container-tight py-4">
        <div class="text-center mb-4">
          <a href="." class="navbar-brand navbar-brand-autodark"><img src="./static/logo.svg" height="36" alt=""></a>
        </div>

        <form class="card card-md" action="./" method="get" autocomplete="off" novalidate="">
            {%csrf_token%}
          <div class="card-body">
            <h2 class="card-title text-center mb-4">Forgot password</h2>
            <p class="text-muted mb-4">Enter your email address and your password will be reset and emailed to you.</p>
            <div class="mb-3">
              <label class="form-label">Email address</label>
              {% for field in form %}
              <div class="form-group mb-3">
                  {{field}}
                  {% if field.errors %}
                  {% for error in field.errors %}
                  <span class="invalid-feedback {%if error%}d-block{%endif%}">{{error}}</span>
                  {% endfor %}
                  {%endif%}
              </div>
              {% endfor %}
              <!-- <input type="email" class="form-control" placeholder="Enter email"> -->
            </div>
            <div class="form-footer">
              <a href="#" class="btn btn-primary w-100">
                <!-- Download SVG icon from http://tabler-icons.io/i/mail -->
                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M3 7a2 2 0 0 1 2 -2h14a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-10z"></path><path d="M3 7l9 6l9 -6"></path></svg>
                Send me new password
              </a>
            </div>
          </div>
        </form>
        <div class="text-center text-muted mt-3">
          Forget it, <a href="{% url 'users:sign_in' %}">send me back</a> to the sign in screen.
        </div>
      </div>
    </div>
</div>
{%endblock content %}

users/templates/users/form_snippets.html
<div class="row lg-3">
    <div class="col-sm-6 {%if center%} mx-auto {%endif%}">
        {% for field in form %}
        <div class="form-group mb-3">
            {{field}}
            {% if field.errors %}
            {% for error in field.errors %}
            <span class="invalid-feedback {%if error%}d-block{%endif%}">{{error}}</span>
            {% endfor %}
            {%endif%}
        </div>
        {% endfor %}
    </div>    
</div>

users/templates/users/home.html
{% extends 'shared_layout/base.html' %}

users/templates/users/login.html
<!DOCTYPE html>
{% extends 'shared_layout/base.html' %}

{%block title%}
login
{%endblock title%}

{%block contents%}
{%if error%}
<div class="alert alert-danger" role="alert">
    {{error}}
</div>
{%endif%}
<form method="post">
    {%csrf_token%}
    {%include 'users/form_snippets.html' with form=form%}                
    <input class="btn btn-primary" type="submit" value="Login">
</form>
<div class="my-2">
    <small class="text-muted">
        Forgot your password ? <a class="ml-2" href="{%url 'users:forgot_password'%}">restore password</a>
    </small>
</div>

<div class="my-2">
    <small class="text-muted">
        Need an account ? <a class="ml-2" href="{%url 'users:register'%}">Sign Up</a>
    </small>
</div>
{%endblock contents%}

users/templates/users/new_password.html
<!DOCTYPE html> {% extends 'shared_layout/base.html' %} 
{%block title%}Create a new password{%endblock title%} 
{%block contents%} 
{%if error%}
<div class="alert alert-danger" role="alert">
    {{error}}
</div>
{%endif%}
<div class="row">
    <div class="col-12 text-center">
        <h5 class="m-2">Reset new password</h5>
        <p class="text-muted">
            Please enter your new password twice so we can verify you typed it in correctly.
        </p>
        <form method="post">
            {%csrf_token%} {%include 'users/form_snippets.html' with center=True form=form%}
            <input class="btn btn-primary" type="submit" value="Change your password">
        </form>
    </div>
</div>
{%endblock contents%}

users/templates/users/register.html
<!DOCTYPE html> {% extends 'shared_layout/base.html' %} {%block title%} register {%endblock title%} {%block contents%} {%if error%}
<div class="alert alert-danger" role="alert">
    {{error}}
</div>
{%endif%}
    <!-- Main navbar  -->
    <div class="page-header d-print-none mt-3 mb-3 py-3">
        <div class="container-xl">
          <div class="row g-2 align-items-center">
            <div class="col">
              <h2 class="logo_">
                OnlyPans
              </h2>
            </div>
            <!-- Page title actions -->
            <div class="col-auto ms-auto d-print-none">
              <a href="{%url 'users:login'%}" class="nav_link">
                Sign in
              </a>
            </div>
          </div>
        </div>
      </div>

      <div class="page">
        <div class="page-wrapper">
          <div class="container-xl">
            <form method="post">
                {%csrf_token%} {%include 'users/form_snippets.html' with form=form%}
            <div class="py-3">
                <div class="pan_label mt-3 mb-3">Email</div>
                <div class="pan_in_wr">
                    <input class="pans_input" placeholder="Email" type="text">
                </div>
            </div>
    
            <div  class="py-3">
                <div class="pan_label mt-3 mb-3">Email</div>
                <div class="pan_in_wr">
                    <input class="pans_input" placeholder="Email" type="text">
                </div>
            </div>
    
            <div  class="py-3">
                <div class="pan_label mt-3 mb-3">Email</div>
                <div class="pan_in_wr">
                    <input class="pans_input" placeholder="Email" type="text">
                </div>
            </div>
            </form>
    
    
                <!-- botom panel  -->
                <div class="container-xl py-4">
                <div type="submit" value="Register" class="botm_right mb-3 mt-3">
                    <div>Welcome to OnlyPans</div>
                    <svg style="width: 40px; height:40px;" xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-circle-arrow-right" width="50px" height="50px" viewBox="0 0 24 24" stroke-width="2" stroke="#490F0A" fill="none" stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                        <path d="M12 3a9 9 0 1 0 0 18a9 9 0 0 0 0 -18"></path>
                        <path d="M16 12l-4 -4"></path>
                        <path d="M16 12h-8"></path>
                        <path d="M12 16l4 -4"></path>
                        </svg>
                </div>
                </div>
          </div>
        </div>
      </div>

{%endblock contents%}

users/templates/users/sign_in.html
{% extends "./base.html" %} 

{% load static %} 

{% block content %}
<body style="background: var(--gray-50, #F9FAFB);">
  <div class="page">
    <div class="page-wrapper">
      <div class=" d-flex flex-column">
        <div class="page page-center">
          <div class="container container-normal py-4">
            <div class="row align-items-center g-4">
              <div class="col-lg">
                <div class="container-tight">
                  <div class="card card-md">
                    <div class="card-body">
                      <h1 class="h1 text-center mb-4">Sign in to your account</h1>
                      <form class="" method="post" autocomplete="off" novalidate="">
                        {%csrf_token%} 
                        {% for field in form %}
            
                        <div class="mb-3">
                            <div class="form-label" style="font-weight: 700;">{{field.name}}</div>
                                {{field}}
                        </div>        
                        {% if field.errors %} {% for error in field.errors %}
                        <span class="invalid-feedback {%if error%}d-block{%endif%}">{{error}}</span>
                        {% endfor %} {%endif%}
                      {% endfor %}
                      <label class="form-label">
                        <span class="form-label-description">
                          <a href="{% url 'users:forgot_password' %}" style="color: #5733E7; font-weight: 700;">I forgot password</a>
                        </span>
                      </label>  
                      <div class="mb-2">
                        <span class="subheader">Password Minimum 8 characters</span>
      
                      </div>
      
                        <div class="mb-2">
                          <label class="form-check">
                            <input type="checkbox" class="form-check-input">
                            <span class="form-check-label">Remember me</span>
                          </label>
                        </div>
                        <div class="form-footer">
                          <button type="submit" class="btn btn-primary w-100" style="background-color: #5733E7;">Sign in</button>
                        </div>
                        
                        {% if SOCIALS %}
                        <div class="hr-text">Or continue with</div>
                        <div class="card-body">
                          <div class="row">
                            <div class="col"><a href="{% url "social:begin" "google-oauth2" %}" class="btn w-100">
                              <svg xmlns="http://www.w3.org/2000/svg" width="25" height="24" viewBox="0 0 25 24" fill="none">
                                <path d="M3.39725 7.51C4.22926 5.85324 5.50563 4.46051 7.08368 3.48747C8.66174 2.51443 10.4793 1.99942 12.3333 2C15.0283 2 17.2923 2.99 19.0233 4.605L16.1563 7.473C15.1193 6.482 13.8013 5.977 12.3333 5.977C9.72825 5.977 7.52325 7.737 6.73825 10.1C6.53825 10.7 6.42425 11.34 6.42425 12C6.42425 12.66 6.53825 13.3 6.73825 13.9C7.52425 16.264 9.72825 18.023 12.3333 18.023C13.6783 18.023 14.8233 17.668 15.7193 17.068C16.2387 16.726 16.6834 16.2822 17.0265 15.7635C17.3695 15.2448 17.6038 14.6619 17.7153 14.05H12.3333V10.182H21.7513C21.8693 10.836 21.9333 11.518 21.9333 12.227C21.9333 15.273 20.8433 17.837 18.9513 19.577C17.2973 21.105 15.0333 22 12.3333 22C11.0199 22.0005 9.71929 21.7422 8.5058 21.2399C7.2923 20.7375 6.1897 20.0009 5.26101 19.0722C4.33232 18.1436 3.59575 17.041 3.09339 15.8275C2.59103 14.614 2.33273 13.3134 2.33325 12C2.33325 10.386 2.71925 8.86 3.39725 7.51Z" fill="#6B7280"/>
                              </svg>
                              </a></div>
                          </div>
                        </div>
                        {% endif %}
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script>
    // Get the first two elements with the class "form-label"
var formLabels = document.querySelectorAll('.form-label');

// Check if there are at least two elements with the class "form-label"
if (formLabels.length >= 2) {
  // Change the text of the first two elements
  formLabels[0].textContent = 'Email';
  formLabels[1].textContent = 'Password';
}

  </script>
</body>


{% endblock %}

users/templates/users/user_otp.html
{% extends "./base.html" %} {% load static %}

{%block title%}
Code Verification
{%endblock title%}

{%block contents%}
{%if error%}
<div class="alert alert-danger" role="alert">
    {{error}}
</div>
{%endif%}
<div class="row">
    <div class="col-12 text-center">
        <h5 class="m-2">Code Verification</h5>
        <p class="text-muted">
            Enter the code witch has been sent to you.
        </p>
        <form method="post">
            {%csrf_token%}
            {%include 'users/form_snippets.html' with center=True form=form%}             
            <input class="btn btn-primary" type="submit" value="Submit">
        </form>    
    </div>
</div>
{%endblock contents%}