app/urls.py
from django.urls import path, include, re_path
from . import views
from django.contrib.auth.decorators import login_required
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.conf import settings
from django.views.static import serve

admin.autodiscover()
admin.site.login = login_required(admin.site.login)

app_name = 'app'

urlpatterns = [    
    path('onboard/', views.Onboard.as_view(), name="onboard"),
    path('dashboard/<str:id>/', views.Dashboard.as_view(), name='dashboard'),
    path('dashboard/', views.Dashboard.as_view(), name="dashboard"),    
    path('api/setup_user/', views.Setup_user.as_view(), name="setup_user"),
    path('api/chat/', views.Chat.as_view(), name="chat"),
    path('api/update_db/', views.Update_db.as_view(), name="update_db"),
    path('user_profile/', views.UserProfile.as_view(), name="user_profile"),
    path('update_profile/', views.Update_profile.as_view(), name='update_profile'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('', include('users.urls')),
    path('', include('subscriptions.urls')),
    path('', include('social_django.urls')),
    path('admin/', admin.site.urls),
]

SOCIAL_AUTH_URL_NAMESPACE = 'social'

subscriptions/urls.py
from django.urls import path, include, re_path
from . import views
from django.contrib.auth.decorators import login_required
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.conf import settings

app_name = 'subscriptions'

urlpatterns = [
    path('upgrade/',  views.Upgrade.as_view(), name='upgrade'),
    path('config/', views.StripeConfig.as_view() , name='config'),
    path('create-checkout-session/', views.Create_checkout_session.as_view(), name='create-checkout-session'),
    path('success/', views.Success.as_view(), name='success'),
    path('cancel/', views.Cancel.as_view() , name='cancel'),
    path('webhook/', views.Stripe_webhook.as_view(), name='webhook'),
]

users/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import (
    login_view,
    logout_view,
    forgot_password_view,
    registeration_view,
    check_otp_view,
    check_reset_otp_view,
    reset_new_password_view,
)

from . import views

app_name = 'users'

urlpatterns = [
    path('', views.Home.as_view(), name="home"),
    path('sign_in/', login_view, name='sign_in'),
    path('logout/', logout_view, name='logout'),
    path('sign_up/', registeration_view, name='sign_up'),
    path('forgot-password/', forgot_password_view, name='forgot_password'),
    path('activate-email/', check_otp_view, name='activate_email'),
    path('reset-code/', check_reset_otp_view, name='reset_code'),
    path('new-password/', reset_new_password_view, name='reset_new_password'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>{% block title %} {% endblock %}</title>

      {% load static %}
      <!-- CSS files -->
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:400,700">
      <script src="https://cdn.jsdelivr.net/npm/@tabler/core@1.0.0-beta17/dist/js/tabler.min.js"></script>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/core@1.0.0-beta17/dist/css/tabler.min.css">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/core@1.0.0-beta17/dist/css/tabler-flags.min.css">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/core@1.0.0-beta17/dist/css/tabler-payments.min.css">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/core@1.0.0-beta17/dist/css/tabler-vendors.min.css">
      <link rel="stylesheet" href="{% static 'css/styles.css' %}">
      <!-- <style>
        @import url('https://rsms.me/inter/inter.css');
        :root {
          --tblr-font-sans-serif: 'Inter Var', -apple-system, BlinkMacSystemFont, San Francisco, Segoe UI, Roboto, Helvetica Neue, sans-serif;
        }
        body {
          font-feature-settings: "cv03", "cv04", "cv11";
        }
      </style> -->
   </head>
   <body>

      {% block navbar %}{% endblock navbar %}
      {% block content %}{% endblock %}

   </body>
</html>

app/templates/home.html
{% extends "./base.html" %}
{% load static %}


{% block content %}
<body class=" border-top-wide border-primary d-flex flex-column">
    <div class="page page-center">
      <div class="container-tight py-4">
        <div class="empty">
          <div class="empty-header">Welcome</div>
          <p class="empty-title">To Zendesk AI chatbot</p>
          <p class="empty-subtitle text-muted">
            You may login or register!
          </p>
          <div class="empty-action">
            <a href="{% url 'users:sign_in' %}" class="btn btn-primary">
                Login
            </a>
            <a href="{% url 'users:sign_up' %}" class="btn btn-primary">
                Register
            </a>
          </div>
        </div>
      </div>
    </div>
</body>
{% endblock %} 

app/templates/onboard.html
{% extends "./base.html" %} 

{% load static %} 

{% block content %}
<body style="background: var(--gray-50, #F9FAFB);">
  <div class="page">
    <div class="page-wrapper">
      <div class=" d-flex flex-column" style="margin: auto;">
        <div class="page page-center">
          <div class="container container-normal py-4">
            <div class="row align-items-center g-4">
              <div class="col-lg">
                <div class="container-tight">
                  <div class="card card-md">
                    <div class="card-body">
                      <h1 class="h1 text-center mb-4">Please provide these details:</h1>
                      <div class="">
                        <div class="mb-3">
                            <div class="form-label" style="font-weight: 700;">Zendesk API token</div>
                                <input type="text" class="form-control" placeholder="token"  required="" id="token">
                        </div>
                        <div class="mb-3">
                            <div class="form-label" style="font-weight: 700;">Your Zendesk subdomain</div>
                                <input type="text" name="username_or_email" class="form-control" placeholder="subdomain"  required="" id="subdomain">
                        </div>
                        <div class="form-footer">
                            <div
                                id="btnup"
                                onclick="setup_user()"
                                class="btn btn_zap w-100 mt-3 mb-3" style="display: flex; gap:15px;"
                            >
                                <div class="spinner-border text-blue" role="status" id="_spinner" style="display: none;"></div>
                                <svg id="_uploadio" xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-upload" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                <path d="M4 17v2a2 2 0 0 0 2 2h12a2 2 0 0 0 2 -2v-2"></path>
                                <path d="M7 9l5 -5l5 5"></path>
                                <path d="M12 4l0 12"></path>
                                </svg>
                                <div id="btn_txt">Continue</div>
                            </div>
                        </div>
                    </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% csrf_token %}
  <script>
function setup_user() {
    document.querySelector('#_spinner').style.display = 'inline-block';
    document.querySelector('#btn_txt').innerHTML = 'Processing<span class="animated-dots"></span>';
    document.querySelector('#_uploadio').style.display = 'none';


  const token = document.getElementById('token');
  const subdomain = document.getElementById('subdomain');

  const url = '/api/setup_user/';
  const data = {
    token: token.value,
    subdomain: subdomain.value
  };
  
  const csrfToken = document.getElementsByName('csrfmiddlewaretoken')[0].value;
  
  fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-CSRFToken': csrfToken,
      },
      body: JSON.stringify(data)
    })
      .then(response => response.json())
      .then(data => {
        console.log(data)
        location.assign("/dashboard/")
      })
      .catch(error => console.error(error));
}

  </script>
</body>


{% endblock %}

app/templates/user_profile.html
{% extends "./base.html" %}
{% load static %}


{% block content %}
  <!-- main Navbar  -->
  <header class="navbar navbar-expand-md d-print-none" style="background-color: #fff; background: #FFF;
  box-shadow: 0px 1px 2px -1px rgba(0, 0, 0, 0.10), 0px 1px 3px 0px rgba(0, 0, 0, 0.10); padding-bottom: 0;">
    <div class="container-xl">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-menu" aria-controls="navbar-menu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <h1 class="navbar-brand navbar-brand-autodark d-none-navbar-horizontal pe-0 pe-md-3" style="border-bottom: 2px solid #6366F1;
      ">
        <img class="{% url 'app:dashboard' %}" src="{% static 'img/logo.png' %}" alt="" style="height: 50px; margin-right: 15px;
        flex: 1 0 0;">
Zendesk AI Bot
      </h1>
      <div class="navbar-nav flex-row order-md-last">
        <div class="nav-item d-none d-md-flex me-3">
          <div class="btn-list">
            {% if user.subscription_status == "true" %}
            <a href="#" class="btn" target="_blank" rel="noreferrer" style="color:#fff; border-radius: 8px;
            background: #9C6CE8;">
              ✨
              Pro
            </a>            
            {% endif %}
            <a href="#" class="btn" target="_blank" rel="noreferrer">
              {{ user.docs_left }} Query left
            </a>
          </div>
        </div>
        <div class="nav-item dropdown">
          <a href="#" class="nav-link d-flex lh-1 text-reset p-0" data-bs-toggle="dropdown" aria-label="Open user menu" style="display: flex;">
            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-user-circle" style="width: 30px; height:30px" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
              <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
              <path d="M12 12m-9 0a9 9 0 1 0 18 0a9 9 0 1 0 -18 0"></path>
              <path d="M12 10m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0"></path>
              <path d="M6.168 18.849a4 4 0 0 1 3.832 -2.849h4a4 4 0 0 1 3.834 2.855"></path>
           </svg>
          </a>
          <div class="dropdown-menu dropdown-menu-end dropdown-menu-arrow p-2" style="border-radius: 15px;line-height:24px; ">
            <div class="flex_bg p-2"><h1 class="header">Account</h1> 
              {% if not user.subscription_status == "true" %}
              <span class="badge badge-outline text-indigo">Free</span>
              {% endif %}


              {% if user.subscription_status == "true" %}
              <span class="badge badge-outline text-indigo">Pro</span>
              {% endif %}
            </div>
            <div class="dropdown-divider"></div>
            <a href="{% url 'app:user_profile' %}" class="dropdown-item" style="flex-direction: column; align-items:flex-start; "><div class="page-title"> {{ user }} </div> <div class="subheader">{{ user.email }} </div>  </a>


            {% if user.subscription_status == "true" %}
            <a href="{% url 'app:user_profile' %}" class="dropdown-item"><svg xmlns="http://www.w3.org/2000/svg" width="21" height="20" viewBox="0 0 21 20" fill="none">
              <g opacity="0.3">
                <path d="M6.33317 3.33333C6.33317 2.8731 5.96007 2.5 5.49984 2.5C5.0396 2.5 4.6665 2.8731 4.6665 3.33333V4.16667H3.83317C3.37293 4.16667 2.99984 4.53976 2.99984 5C2.99984 5.46024 3.37293 5.83333 3.83317 5.83333H4.6665V6.66667C4.6665 7.1269 5.0396 7.5 5.49984 7.5C5.96007 7.5 6.33317 7.1269 6.33317 6.66667V5.83333H7.1665C7.62674 5.83333 7.99984 5.46024 7.99984 5C7.99984 4.53976 7.62674 4.16667 7.1665 4.16667H6.33317V3.33333Z" fill="#5733E7"/>
                <path d="M5.49984 13.3333C5.49984 12.8731 5.12674 12.5 4.6665 12.5C4.20627 12.5 3.83317 12.8731 3.83317 13.3333V14.1667H2.99984C2.5396 14.1667 2.1665 14.5398 2.1665 15C2.1665 15.4602 2.5396 15.8333 2.99984 15.8333H3.83317V16.6667C3.83317 17.1269 4.20627 17.5 4.6665 17.5C5.12674 17.5 5.49984 17.1269 5.49984 16.6667V15.8333H6.33317C6.79341 15.8333 7.1665 15.4602 7.1665 15C7.1665 14.5398 6.79341 14.1667 6.33317 14.1667H5.49984V13.3333Z" fill="#5733E7"/>
              </g>
              <path d="M12.1087 3.02759C11.9832 2.70923 11.6757 2.5 11.3335 2.5C10.9913 2.5 10.6838 2.70923 10.5583 3.02759L9.09758 6.73123C8.9257 7.16705 8.88649 7.25055 8.84052 7.31473C8.78738 7.38893 8.72242 7.45389 8.64823 7.50702C8.58404 7.55299 8.50055 7.5922 8.06473 7.76408L4.36109 9.22478C4.04273 9.35034 3.8335 9.65777 3.8335 10C3.8335 10.3422 4.04273 10.6497 4.36109 10.7752L8.06473 12.2359C8.50055 12.4078 8.58404 12.447 8.64823 12.493C8.72242 12.5461 8.78738 12.6111 8.84052 12.6853C8.88649 12.7495 8.9257 12.8329 9.09758 13.2688L10.5583 16.9724C10.6838 17.2908 10.9913 17.5 11.3335 17.5C11.6757 17.5 11.9832 17.2908 12.1087 16.9724L13.5694 13.2688C13.7413 12.8329 13.7805 12.7495 13.8265 12.6853C13.8796 12.6111 13.9446 12.5461 14.0188 12.493C14.0829 12.447 14.1664 12.4078 14.6023 12.2359L18.3059 10.7752C18.6243 10.6497 18.8335 10.3422 18.8335 10C18.8335 9.65777 18.6243 9.35034 18.3059 9.22478L14.6023 7.76408C14.1664 7.5922 14.0829 7.55299 14.0188 7.50702C13.9446 7.45389 13.8796 7.38893 13.8265 7.31473C13.7805 7.25055 13.7413 7.16705 13.5694 6.73123L12.1087 3.02759Z" fill="#5733E7"/>
            </svg> Subscription</a>
            {% endif %}


            {% if user.user_plan == "Free" %}
            <a href="{% url 'subscriptions:upgrade' %}" class="dropdown-item"><svg xmlns="http://www.w3.org/2000/svg" width="21" height="20" viewBox="0 0 21 20" fill="none">
              <g opacity="0.3">
                <path d="M6.33317 3.33333C6.33317 2.8731 5.96007 2.5 5.49984 2.5C5.0396 2.5 4.6665 2.8731 4.6665 3.33333V4.16667H3.83317C3.37293 4.16667 2.99984 4.53976 2.99984 5C2.99984 5.46024 3.37293 5.83333 3.83317 5.83333H4.6665V6.66667C4.6665 7.1269 5.0396 7.5 5.49984 7.5C5.96007 7.5 6.33317 7.1269 6.33317 6.66667V5.83333H7.1665C7.62674 5.83333 7.99984 5.46024 7.99984 5C7.99984 4.53976 7.62674 4.16667 7.1665 4.16667H6.33317V3.33333Z" fill="#5733E7"/>
                <path d="M5.49984 13.3333C5.49984 12.8731 5.12674 12.5 4.6665 12.5C4.20627 12.5 3.83317 12.8731 3.83317 13.3333V14.1667H2.99984C2.5396 14.1667 2.1665 14.5398 2.1665 15C2.1665 15.4602 2.5396 15.8333 2.99984 15.8333H3.83317V16.6667C3.83317 17.1269 4.20627 17.5 4.6665 17.5C5.12674 17.5 5.49984 17.1269 5.49984 16.6667V15.8333H6.33317C6.79341 15.8333 7.1665 15.4602 7.1665 15C7.1665 14.5398 6.79341 14.1667 6.33317 14.1667H5.49984V13.3333Z" fill="#5733E7"/>
              </g>
              <path d="M12.1087 3.02759C11.9832 2.70923 11.6757 2.5 11.3335 2.5C10.9913 2.5 10.6838 2.70923 10.5583 3.02759L9.09758 6.73123C8.9257 7.16705 8.88649 7.25055 8.84052 7.31473C8.78738 7.38893 8.72242 7.45389 8.64823 7.50702C8.58404 7.55299 8.50055 7.5922 8.06473 7.76408L4.36109 9.22478C4.04273 9.35034 3.8335 9.65777 3.8335 10C3.8335 10.3422 4.04273 10.6497 4.36109 10.7752L8.06473 12.2359C8.50055 12.4078 8.58404 12.447 8.64823 12.493C8.72242 12.5461 8.78738 12.6111 8.84052 12.6853C8.88649 12.7495 8.9257 12.8329 9.09758 13.2688L10.5583 16.9724C10.6838 17.2908 10.9913 17.5 11.3335 17.5C11.6757 17.5 11.9832 17.2908 12.1087 16.9724L13.5694 13.2688C13.7413 12.8329 13.7805 12.7495 13.8265 12.6853C13.8796 12.6111 13.9446 12.5461 14.0188 12.493C14.0829 12.447 14.1664 12.4078 14.6023 12.2359L18.3059 10.7752C18.6243 10.6497 18.8335 10.3422 18.8335 10C18.8335 9.65777 18.6243 9.35034 18.3059 9.22478L14.6023 7.76408C14.1664 7.5922 14.0829 7.55299 14.0188 7.50702C13.9446 7.45389 13.8796 7.38893 13.8265 7.31473C13.7805 7.25055 13.7413 7.16705 13.5694 6.73123L12.1087 3.02759Z" fill="#5733E7"/>
            </svg> Upgrade to premium</a>
            {% endif %}

            

            <a href="{% url 'users:logout' %}" class="dropdown-item" style="display: flex; justify-content:space-between;"><span>Sign out</span> <span class="float:right"><svg xmlns="http://www.w3.org/2000/svg" width="21" height="20" viewBox="0 0 21 20" fill="none">
              <path d="M8 5L13 10L8 15" stroke="#475467" stroke-width="1.66667" stroke-linecap="round" stroke-linejoin="round"/>
            </svg></span></a>
          </div>
        </div>
      </div>
    </div>
  </header>



<div class="page">
    <div class="page-wrapper">
        <!-- Page header -->
        <div class="page-header d-print-none py-3">
          <div class="container-xl">
            <div class="row g-2 align-items-center">
              <div class="col">
                <h2 class="page-title text-center">
                  Account Settings
                </h2>
              </div>
            </div>
          </div>
        </div>


        <!-- Page body -->
        <div class="page-body">
          <div class="container-xl">
            <div class="card">
              <div class="row g-0">
                <div class="col-12 col-md-3 border-end">
                  <div class="card-body">
                    <h4 class="subheader">Account settings</h4>
                    <div class="list-group list-group-transparent">
                      <a href="./settings.html" class="list-group-item list-group-item-action d-flex align-items-center active">My Account</a>
                      <a href="{% url 'app:dashboard' %}" class="list-group-item list-group-item-action d-flex align-items-center">Dashboard</a>
                      <a href="{% url 'subscriptions:upgrade' %}" class="list-group-item list-group-item-action d-flex align-items-center">Upgrade</a>
                    </div>
                  </div>
                </div>
                <div class="col-12 col-md-9 d-flex flex-column">
                  <div class="card-body">
                    <h2 class="mb-4">My Account</h2>
                    <h3 class="card-title mt-4">Profile Details</h3>
                    <div class="row g-3">
                      <div class="col-md">
                        <div class="form-label">First Name</div>
                        <input type="text" class="form-control" value="{{ user.first_name }}" id="first_">
                      </div>
                      <div class="col-md">
                        <div class="form-label">Last Name</div>
                        <input type="text" class="form-control" value="{{ user.last_name }}" id="sec_">
                      </div>
                    </div>
                    <h3 class="card-title mt-4">Email</h3>
                    <p class="card-subtitle">This is your email address.</p>
                    <div>
                      <div class="row g-2">
                        <div class="col-auto">
                          <input type="text" class="form-control w-auto" value="{{ user.email }}" id="email">
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="card-footer bg-transparent mt-auto">
                    <div class="btn-list justify-content-end">
                      <a href="#" class="btn btn-primary" onclick="update_profile()" style="border-radius: 8px;
                      border: 1px solid var(--secondary-600, #F9B60A);
                      background: var(--secondary-600, #F9B60A);
                      ">
                        Save Changes
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

    <!-- page footer  -->
    <footer class="footer footer-transparent d-print-none">
      <div class="container-xl">
        <div class="row text-center align-items-center flex-row-reverse">
          <div class="col-12 col-lg-auto mt-3 mt-lg-0">
            <ul class="list-inline list-inline-dots mb-0">
              <li class="list-inline-item">
                Copyright © 2023
                <a href="." class="link-secondary">Zendesk AI Bot</a>.
                All rights reserved.
              </li>
              <li class="list-inline-item">
                <a href="./changelog.html" class="link-secondary" rel="noopener">
                  v1.0.0
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
      </div>
</div>
{% csrf_token %}
<script>
  const csrfToken = document.getElementsByName("csrfmiddlewaretoken")[0].value;


  function update_profile() {
    var first_ = document.querySelector("#first_").value;
    var sec_ = document.querySelector("#sec_").value;
    var email = document.querySelector("#email").value;

    const data = {
      email: email,
      first_: first_,
      sec_: sec_
    };
  
    const csrfToken = document.getElementsByName("csrfmiddlewaretoken")[0].value;
  
    fetch('/update_profile/', {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-CSRFToken": csrfToken,
      },
      body: JSON.stringify(data),
    })
      .then((response) => response.json())
      .then((data) => {
        var jsonData = data.output;
        location.reload();
      })
      .catch((error) => console.error(error));

  }
</script>
{% endblock %} 